### ISSUE TITLE
Stub of esa.io API

### ISSUE THREAD

**Issue by usagiga** [usagiga/essay#6]
To test this project in offline, prepare stub of esa.io API.

# Tasks

- [x] Prepare stub data for [JSON Server](https://github.com/typicode/json-server)
- [x] Prepare `docker-compose.yml` for develop
    - [x] Use [Docker JSON Server](https://github.com/clue/docker-json-server)
- [x] Prepare test data
    - [x] Compatible with page nation
- [x] Prepare `.env.development` for Docker
- [x] Run it on GitHub Actions

# References

- [Basic Features: Environment Variables | Next.js](https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables)
- [Basic Features: Data Fetching | Next.js](https://nextjs.org/docs/basic-features/data-fetching)

**Comment by usagiga** [comment]
Done!
